server:
  port: 8191
spring:
  profiles:
    active: native
  application:
    name: CONFIG-SERVER
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}