server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: hossein
    driverClassName: com.mysql.cj.jdbc.Driver
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
#================================= For Cloud config (in my case Local config server)
  config:
    #----------read from Local config
    import: configserver:http://localhost:8191
    #----------read from Git
    #import: https://github.com/HosseinJavooni/springAppConfig
#================================= Uncomment lines below when you don't want to get config from cloud config server
#  cloud:
#    config:
#      enabled: false
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}